### ISSUE TITLE
Shortcodes Order

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson-WP-Shortcodes-Extension#3]
Make it work with the hook we have in Page Builder. Maybe this hook should be moved in Shortcodes extension?

cc. @moldcraft

**Comment by ghost** [comment]
> Maybe this hook should be moved in Shortcodes extension?
1. It is already used by people, so it will be like that forever.
2. Or if you know how to move it but to maintain the compatibility, then do it.
3. But maybe somebody will want one order in PageBuilder and another order in WP-Shortcodes? So the hooks should be separated.

**Comment by andreiglingeanu** [comment]
> But maybe somebody will want one order in PageBuilder and another order in WP-Shortcodes? So the hooks should be separated.

I kinda like that one. Maybe default to alphabetical order and introduce one more hook.
