### ISSUE TITLE
Section duplicate gone wrong

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson-WP-Shortcodes-Extension#5]
I've duplicated the section shortcode. Everything cool on the back-end. On front, it gives me something like [this](http://prntscr.com/cmtqxf)

Am I missing something?

**Comment by dmbostan** [comment]
It seems that it renders [sectionvideo][column] ... [/sectionvideo][/column]

**Comment by dmbostan** [comment]
anyone?

**Comment by andreiglingeanu** [comment]
Are you trying to add columns in `wp-editor`?

Adding structural shortcodes into the `wp-editor` is not supported by this extension and I'm not sure it will even work.

**Comment by dmbostan** [comment]
I guess. i work in Page Builder, but I gues it uses the WP editor.

**Comment by dmbostan** [comment]
True, but I can use `section` in Page Builder, right? The strange thing is that it ouputs [section] and [sectionvideo] in [2 different ways](http://prntscr.com/cmutw5)

If I could filter the way it renders, i guess I can be good to go.

**Comment by andreiglingeanu** [comment]
> True, but I can use section in Page Builder, right? 

Right.

Please try to describe what you are trying to achieve. Where's the `sectionvideo` shortcode coming from?

**Comment by dmbostan** [comment]
[sectionvideo] is an exact copy of [section], just with some specific options.
In shortcode files, all section text was replaced with sectionvideo, and Section_ to Sectionvideo_

**Comment by dmbostan** [comment]
Maybe, there is a filter to add to tell Page Builder to parse sectionvideo as section?

**Comment by dmbostan** [comment]
If you want, I can send you the files.

**Comment by dmbostan** [comment]
Any result?

**Comment by ghost** [comment]
Hello @dmbostan 

We support our built-in shortcodes: section, row, column and other.
You created your own shortcode and ask us why it doesn't work. Section is not a simple shortcode and it will be hard to help you in this case. Try to to make a file compare between your and built-in section shortcode and find the problem.

You are describing the the shortcode syntax is broken, this is most likely because you are using wrongly the encoder which encodes/decodes shortcode attributes, please pay attention to that.

**Comment by dmbostan** [comment]
True, this is not a built-in shortcode, therefore it shall not be supported. However, would really like to see this implemented and eventually documented, because I think I am not the only one needing this functionality.

Now ...

> this is most likely because you are using wrongly the encoder which encodes/decodes shortcode attributes

Where exactly should I look?

**Comment by ghost** [comment]
You have looked in frontend and the shortcodes are broken (panic).
Try to debug the code execution and find the place where the shortcodes are generated and why they become broken (debug with `var_dump();`, `die;`, `debug_print_backtrace();`, ...)

The starting point is [this](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/649fe08a568e468f1ec5e5854ef89cc6efc1d53a/class-fw-extension-page-builder.php#L382), here the builder json is transformed to shortcodes text.

**Comment by dmbostan** [comment]
@moldcraft , you were right. It seems it is because of this

```
if ($this->needs_correction()) {
            $corrector             = new _Page_Builder_Items_Corrector($this->get_item_types());
            $corrected_items_value = $corrector->correct($items_value);

            return $this->get_shortcode_notation($corrected_items_value);
        } else {
            return $this->get_shortcode_notation($items_value);
        }
```

I added the $cfg['disable_correction'] = true; (also disalbe) to `parent-theme/framework-customizations/extensions/builder/config.php` but it is not working.

Changed to true from pugin, but that is not the right way to do it.

Any idea how I could overwrite this value without editing plugin files?

**Comment by dmbostan** [comment]
In addition

```
add_action(
    'fw_ext_shortcodes_enqueue_static:sectionvideo',
    '_action_theme_shortcode_sectionvideo_enqueue_dynamic_css'
);
```

is not working. 

This was solved. Not a duplication issue.

**Comment by dmbostan** [comment]
so, how can I change $cfg['disable_correction'] without editing plugin files ?

**Comment by ghost** [comment]
Please read [this](http://manual.unyson.io/en/latest/extensions/introduction.html#directory-structure)

**Comment by dmbostan** [comment]
... and that is exactly what I did. Added $cfg['disable_correction'] = true; in parent theme and child-theme. Tried to var_dump and it prints `true`. However it really works when I am changing from the plugin config.

**Comment by ghost** [comment]
> However it really works when **I am changing from the plugin config**

Show us where exactly, which config?

**Comment by dmbostan** [comment]
theme/framework-customizations/extensions/builder/config.php

**Comment by ghost** [comment]
@dmbostan There is no `$cfg['disable_correction'] = true;` in [builder/config.php](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/3fc599a94b7607088ed684335b97d827ddb2d422/config.php)

**Comment by ghost** [comment]
Please search `disable_correction` in all Unyson extensions and check how it works.

**Comment by dmbostan** [comment]
@moldcraft yes, there is none of this, but I need it to make it like this.
