### ISSUE TITLE
Problem with custom shortcode

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-WP-Shortcodes-Extension#8]
We have a revolution slider shortcode, in config.php we add the shortcode only when the plugin is active. something like this: 
```
if( class_exists('RevSlider') ) {
    $cfg = array(
        'page_builder' => array(
            'title'                 => __( 'Revolution Slider', 'the-core' ),
                        // ...
               )
        )
}
```

In visual builder, all works fine, but in wp-shortcodes looks like this: https://static.md/2fc85712a67c4f607eb25d187b979fd3.png

In shortcodes array come this: https://static.md/4b124730e685f827e06554672912b839.png . Can you make a verification to fix this problem and for another shortcodes like this?

Thank you!

**Comment by andreiglingeanu** [comment]
The check should not be in the `config.php` file. You should use the standard filter in order to disable shortcodes, like that:

```php
function _fw_disable_shortcodes($to_disable) {
	if ( ! class_exists('RevSlider') ) {
		$to_disable = array_merge( $to_disable, 'revolution-slider-shortcode');
	}

	return $to_disable;
}

add_filter('fw_ext_shortcodes_disable_shortcodes', '_fw_disable_shortcodes');
```

[Here's](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/efb988cc467826e3fd1f9c9bbabf5afd62f74e4a/class-fw-extension-shortcodes.php#L201) where the filter is located.

**Comment by thednp** [comment]
@andreiglingeanu / @ViorelEremia 


I developed some shortocodes to build others based on their options, like you see below, so I don't want those to be shown in the `wp-shortcode` extension.

I do it like this and is ***not working*** with `wp-shortocode` extension:

```php
function _fw_disable_wp_shortcodes($to_disable) {
  $to_disable[] = 'button-base';
  $to_disable[] = 'color-settings';
  $to_disable[] = 'size-settings';
  return $to_disable;
}

add_filter('fw_ext_shortcodes_disable_shortcodes', '_fw_disable_wp_shortcodes');
```

I think we need a `fw_ext_wp_shortcodes_disable_shortcodes` filter to work with `wp-shortcodes` extension.

**Comment by andronic90** [comment]
Hi,

try this:

```
function _fw_disable_wp_shortcodes($to_disable) {
  $to_disable[] = 'button_base';
  $to_disable[] = 'color_settings';
  $to_disable[] = 'size_settings';
  return $to_disable;
}
```

**Comment by thednp** [comment]
It's the exact same thing man. What am I missing?

**Comment by andronic90** [comment]
'button_base' not 'button-base'

**Comment by thednp** [comment]
Indeed it is `_` (underscore) instead of `-` (dash), I completely forgot about that, however the filter will also disable these shortcodes for the page builder, I wish the filter would apply to the `wp-shortcodes` extension shortcodes *display* only.

**Comment by thednp** [comment]
OK here's what I ended up with:

```php
// Filter out the utility shortcodes
function _fw_disable_wp_shortcodes($list) {
  // default shortcodes
  $shortcodes = array_keys( fw_ext('shortcodes')->get_shortcodes() );

  // custom built shortcodes
  $customs_shortcodes = array( 'button_base', 'color_settings', 'size_settings' );

  $list = array_diff(
    apply_filters( 'fw:ext:wp-shortcodes:default-shortcodes',
      array_diff( $shortcodes, $customs_shortcodes ) 
    ),
    $customs_shortcodes
  );
    
  sort( $list );

  $list = apply_filters(
    'fw:ext:wp-shortcodes:sort', $list
  );

  return $list;
}
add_filter('fw_init', '_fw_disable_wp_shortcodes');

```

Now the `$list` array looks good, but I'm still getting those shortcodes displayed in the `wp-shortcodes` no matter what. Investigating further I found out it's the `plugin.js` job to render the window and shortocode buttons, that's where we might have to check.

I'm sure that the data sent must be properly filtered via PHP, really the better way.

@andreiglingeanu @alexluncashu @ViorelEremia can any of you have a look at this please.

**Comment by thednp** [comment]
I think I will resort to a quick JavaScript hack in the meantime.
