### ISSUE TITLE
WP Shortcodes in WP editor (Unyson option type)

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson-WP-Shortcodes-Extension#9]
I've activated the WP Shortcodes extension. This adds the shortcode button to the standard WP editor.

But: the shortcode button is not added to a WP editor that I add in Theme Settings.

I've read a few threads about this, but I can't really find a solution for this.

Is there a solution available to make the WP shortcodes extension work in this situation?

Hope to hear from you, thanks in advance!
-Kevin

**Comment by ViorelEremia** [comment]
Add the key ```'shortcodes' => true``` exemple: 
```
array(
    'type'  => 'wp-editor',
    'value' => 'default value',
    'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
    'label' => __('Label', '{domain}'),
    'desc'  => __('Description', '{domain}'),
    'help'  => __('Help tip', '{domain}'),
    'size' => 'small', // small, large
    'editor_height' => 400,
    'wpautop' => true,
    'editor_type' => false, // tinymce, html
    'shortcodes' => true
)
```
Close the issue if everything is fine

**Comment by noesteijver** [comment]
Ahh, I didn't know about the shortcodes option. It's working now, thanks!
